import sys

def FAIL(message):
  print(message)
  sys.exit()
